CREATE TABLE IF NOT EXISTS company (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    cnpj TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS update_company_updated_at
AFTER UPDATE ON company
FOR EACH ROW
BEGIN
    UPDATE company
    SET updated_at = CURRENT_TIMESTAMP
    WHERE id = OLD.id;
END;
